4 ncnews
RyanJMarsh/BE_NC_News pull request #4
Opened 2022-12-13 16:13 UTC by RyanJMarsh

2022-12-13 16:48 UTC, johnhutcheon requested changes
Great work Ryan! Just check my comment about moving the error. It looks like this also needs to be done for Ticket 5 from Jodie's feedback, so please implement this. 
Let me know once you've done it with a message on Slack and I'll approve 👍

2022-12-13 16:48 UTC, johnhutcheon commented on __tests__/app.test.js
> +            author: expect.any(String),
Could we be more specific with the author to expect the username of the author please?

2022-12-13 16:48 UTC, johnhutcheon commented on __tests__/app.test.js
> +  });
Please add one more 200 test for a valid ID which has no comments, so would return an empty array of comments 👍

2022-12-13 16:48 UTC, johnhutcheon commented on controllers/app.controllers.js
> +      if (comments.length === 0) {
This error handling is good, but please it move it into the model 👍

2022-12-13 17:02 UTC, RyanJMarsh commented on __tests__/app.test.js
> +            author: expect.any(String),
Not sure how to make it more specific? It's the comment author not article author so it won't all be the same for a particular article_id

2022-12-14 09:14 UTC, johnhutcheon commented on __tests__/app.test.js
> +            author: expect.any(String),
Sorry my bad, ignore this comment!

2022-12-15 16:37 UTC, merged